apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-olivetti-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mlops-olivetti
  template:
    metadata:
      labels:
        app: mlops-olivetti
    spec:
      containers:
        - name: mlops-olivetti-container
          image: your-dockerhub-bharadwajkavuri/olivetti-mlops:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-olivetti-service
spec:
  type: LoadBalancer
  selector:
    app: mlops-olivetti
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
